nodeLinker: node-modules
nmHoistingLimits: none
enableGlobalCache: false
enableImmutableInstalls: false
checksumBehavior: update
supportedArchitectures:
  os: ["current"]
  cpu: ["current"]
compressionLevel: mixed
enableNetwork: true
httpTimeout: 60000
